version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d 
      - ./v3/schema-3.sql:/schemas/schema.sql
    ports:
      - "5432:5432"

  gateway:
    build: ./v3/gateway
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  payment-service:
    build: ./v3/payment-service
    ports:
      - "8050:8050"
    depends_on:
      - postgres

  rental-service:
    build: ./v3/rental-service
    ports:
      - "8060:8060"
    depends_on:
      - postgres

  cars-service:
    build: ./v3/cars-service
    ports:
      - "8070:8070"
    depends_on:
      - postgres

volumes:
  db-data:
